version: '3.8'
services:

    watchdog_core:
        image: vobilyk/watchdog_core:latest
        container_name: 'watchdog_core'
        restart: on-failure
        networks:
            - back
        ports:
            - "5050:5050"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        env_file:
            - /etc/environment
        volumes:
           - ./resources:/app/Resources

    watchdog_collector:
        image: vobilyk/watchdog_collector:latest
        container_name: 'watchdog_collector'
        restart: on-failure
        networks:
            - back
        ports:
            - "5090:5090"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        env_file:
            - /etc/environment
            
    watchdog_loader:
        image: vobilyk/watchdog_loader:latest
        container_name: 'watchdog_loader'
        restart: on-failure
        networks:
            - back
        ports:
            - "5110:5110"
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
        env_file:
            - /etc/environment

    watchdog_notifier:
        image: vobilyk/watchdog_notifier:latest
        container_name: 'watchdog_notifier'
        restart: on-failure
        networks:
            - back
        ports:
            - "5070:5070"
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
        env_file:
            - /etc/environment

    watchdog_emailer:
        image: vobilyk/watchdog_emailer:latest
        container_name: 'watchdog_emailer'
        restart: on-failure
        networks:
            - back
        ports:
            - "5130:5130"
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
        env_file:
            - /etc/environment

    watchdog_frontend:
        depends_on:
            - watchdog_core
            - watchdog_collector
            - watchdog_notifier
            - watchdog_loader
            - watchdog_emailer
        image: vobilyk/watchdog_frontend:latest
        container_name: 'watchdog_frontend'
        restart: on-failure
        networks:
            - back
            - front
        ports:
            - "80:80"
            - "443:443"
        volumes:
           - /etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/cert.pem:/etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/cert.pem
           - /etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/chain.pem:/etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/chain.pem
           - /etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/fullchain.pem:/etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/fullchain.pem
           - /etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/privkey.pem:/etc/letsencrypt/live/bsa-watchdog.westeurope.cloudapp.azure.com/privkey.pem

networks:
    back:
        driver: bridge
    front:
        driver: bridge
